import { useEffect } from 'react';
import Head from 'next/head';
import Header from './Components/Header';
import Introduction from './Components/Introduction';
import Views from './Components/Views';
import Trip from './Components/Trip';
import Footer from './Components/Footer';

import Lenis from 'lenis';
import { SpeedInsights } from '@vercel/speed-insights/next';

export default function Home() {
    useEffect(() => {
        const lenis = new Lenis();

        function raf(time) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);
    }, []);

    return (
        <>
            <Head>
                <title>Volcanic Wonder</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <>
                <Header />
                <Introduction />
                <Views />
                <Trip />
                <Footer />
                <SpeedInsights />
            </>
        </>
    );
}
